name: Spoolman Server
description: Run the latest stable version of Spoolman.
url: https://github.com/lfpoulain/Spoolman
slug: spoolman_server
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
udev: true
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
environment:
  SPOOLMAN_DIR_DATA: "/config"
  PUID: "0"
  PGID: "0"
map:
  - addon_config:rw
boot: auto
ports:
  8000/tcp: 8000
image: ghcr.io/donkie/spoolman
version: 0.21
